### ISSUE TITLE
Question about initialization in class MyConvo2d?

### ISSUE THREAD

**Issue by jionie** [jalola/compare-tensorflow-pytorch#1]
Hi! Thanks for your great code! I have one question about weights initialization in MyConvo2d. It seems that you had set self.he_init = he_init, but you didn't use it. And in test_compare_tf_to.py, weights_init(m) seems don't use he_init too.

**Comment by jalola** [comment]
Hi Joinie,

Yes, we don't use random weight initialization in this repo because this is testing repo (of course we do use he_init in [main GAN repo](https://github.com/jalola/improved-wgan-pytorch)).

As we mentioned in the README: "We inject the same weights init and inputs into layers of TensorFlow and Pytorch that we want to compare. For example, we set 5e-2 for the weights of Conv2d layer in both TensorFlow and Pytorch. Then we passed the same random input to those 2 layers and finally we compared 2 outputs from TensorFlow tensor and Pytorch tensor."

We assign weight = 0.05 here:

- For Pytorch: https://github.com/jalola/compare-tensorflow-pytorch/blob/master/test/test_compare_tf_to.py#L22

- For TensorFlow: https://github.com/jalola/compare-tensorflow-pytorch/blob/master/test/tflib/ops/conv2d.py#L11

Hope it clarifies.
